<font size="5"><b><center>CS:GO Professional Matches Analysis</center></b></font>
<center><b>Dataset: </b>CS:GO Professional Matches - <b>Date: </b>March 26, 2020</center>

# Index
1. [Introduction](#Introduction)<br>
2. [Preparation](#Preparation)<br>
3. [Results DataFrame](#Results-DataFrame)<br>
3.1. [Distribution of scores](#Distribution-of-scores)<br>
3.2. [Most CT-sided map](#Most-CT-sided-map)<br>
3.3. [Maps played per period](#Maps-played-per-period)<br>
3.4. [Best teams on each map](#Best-teams-on-each-map)<br>
4. [Economy DataFrame](#Economy-DataFrame)<br>
4.1. [Round victory probability by equipment value](#Round-victory-probability-by-equipment-value)<br>
4.2. [Pistols ranking](#Pistols-ranking)<br>
5. [Players DataFrame](#Players-DataFrame)<br>
5.1.  [Players ranking by map](#Players-ranking-by-map)<br>
5.2. [Players ranking all maps](#Players-ranking-all-maps)<br>
5.3. [K/D Graph](#K/D-Graph)<br>
6. [Picks DataFrame](#Picks-DataFrame)<br>
7. [Further exploration and predictions](#Further-exploration-and-predictions)<br>

# Introduction

<b>Background:</b> The data used in this notebook was collected at https://www.hltv.org/results. It was scraped off using the libraries 'requests' and 'BeautifulSoup'.

I haven't set any specific goal for this analysis, the idea was just to explore the data and see what information I could get. Also, I tried to avoid computing statistics that are easily obtained in e-sports websites (team victory percentage, average k/d ratio per player, etc.) and instead focused on rankings and analysis with temporal aspects.

This is my first public kernel, so don't hesitate in giving me corrections and suggestions.

Let's get started!

# The Game

This section is copied from the Dataset description.

Counter-Strike Global Offensive is a game released in 2012, as a sequel to Counter-Strike Source (released in 2004), which is itself a sequel to the original Counter-Strike (released in 2000). The game's longevity is primarily caused by its competitive approach and vibrant professional scene. This longevity has shown in numbers recently, as CS:GO reached in March its all-time high concurrent weekly players (1.1M players), making it the most played game on Steam, 7 years after it was launched.

The game retains the same gameplay concepts since its first version, which include a Terrorist side (T) that is tasked to plant a bomb and have it detonate, and a Counter-Terrorist side (CT) that is tasked to defuse the bomb or prevent it from being planted. Both teams can also win a round by eliminating all players on the opposing team before the bomb is planted.

A standard game of Counter-Strike is a best of 30 rounds, the winning team being the first to win 16 rounds. The 30 rounds are played in two halves of 15 on each side of the map, with a round time limit of 1 minute 55 seconds, plus 40 seconds after the bomb is planted.

In case both teams draw at the 30th round on 15x15, 6 more rounds are added-on, which constitutes overtime. The overtime ends if a team wins 4 out of 6 rounds. If both teams win 3 rounds in overtime, another overtime of 6 rounds is played, and the process might repeat indefinitely until one team wins it.

There are 7 maps in the map pool that are available to be played competitively at any given time. Maps are removed and added frequently for updates and revamps, as to not make the game stale. Matches are normally played as a 'bo3' (Best of 3) maps, with less important matches played in a 'bo1' fashion and finals often played as 'bo5's.

There is a money management side to rounds in Counter-Strike. This side is detailed in the 'Economy DataFrame' topic.

# Preparation

Importing libraries and loading the tables.

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from os import listdir

pd.set_option('display.max_columns',100)

listdir('../input/csgo-professional-matches/')

['picks.csv', 'players.csv', 'economy.csv', 'results.csv']

In [2]:
base_dir = '../input/csgo-professional-matches/'

results_df = pd.read_csv(base_dir+'results.csv',low_memory=False)
picks_df = pd.read_csv(base_dir+'picks.csv',low_memory=False)
economy_df = pd.read_csv(base_dir+'economy.csv',low_memory=False)
players_df = pd.read_csv(base_dir+'players.csv',low_memory=False)

The first rows of each table are presented below. The data is split into 4 tables that store data related to:

 - <b>results_df:</b>   &nbsp;  map scores and team rankings

 - <b>picks_df:</b> &nbsp;  order of map picks and vetos in the map selection process.

 - <b>economy_df:</b>  &nbsp;  round start equipment value for all rounds played

 - <b>players_df:</b> &nbsp;   individual performances of players in each map.
 
Values stored in 'event_id' and 'match_id' columns are unique for each match and event and shared between dataframes, so these columns can be used as keys to merge data between dataframes.

It is necessary to note that the rows in 'results_df' and 'economy_df' store data for each map played in a match, while the rows in 'picks_df' and 'players_df' store data for the entire match.

In [3]:
results_df.head()

date               team_1          team_2     _map  result_1  \
0  2020-03-18              Recon 5         TeamOne    Dust2         0   
1  2020-03-18              Recon 5         TeamOne  Inferno        13   
2  2020-03-18  New England Whalers        Station7  Inferno        12   
3  2020-03-18              Rugratz  Bad News Bears  Inferno         7   
4  2020-03-18              Rugratz  Bad News Bears  Vertigo         8   

   result_2  map_winner  starting_ct  ct_1  t_2  t_1  ct_2  event_id  \
0        16           2            2     0    1    0    15      5151   
1        16           2            2     8    6    5    10      5151   
2        16           2            1     9    6    3    10      5243   
3        16           2            2     0    8    7     8      5151   
4        16           2            2     4    5    4    11      5151   

   match_id  rank_1  rank_2  map_wins_1  map_wins_2  match_winner  
0   2340454      62      63           0           2             2  
1   2340454      62      63           0           2             2  
2   2340461     140     118          12          16             2  
3   2340453      61      38           0           2             2  
4   2340453      61      38           0           2             2

In [4]:
picks_df.head()

date               team_1          team_2  inverted_teams  match_id  \
0  2020-03-18              TeamOne         Recon 5               1   2340454   
1  2020-03-18              Rugratz  Bad News Bears               0   2340453   
2  2020-03-18  New England Whalers        Station7               0   2340461   
3  2020-03-17           Complexity           forZe               1   2340279   
4  2020-03-17          Singularity        Endpoint               0   2340456   

   event_id best_of  system t1_removed_1 t1_removed_2 t1_removed_3  \
0      5151       3  123412      Vertigo        Train          0.0   
1      5151       3  123412        Dust2         Nuke          0.0   
2      5243       1  121212       Mirage        Dust2      Vertigo   
3      5226       3  123412      Inferno         Nuke          0.0   
4      5247       3  123412        Train       Mirage          0.0   

  t2_removed_1 t2_removed_2 t2_removed_3 t1_picked_1 t2_picked_1 left_over  
0         Nuke     Overpass          0.0       Dust2     Inferno    Mirage  
1       Mirage        Train          0.0     Vertigo     Inferno  Overpass  
2         Nuke        Train     Overpass         0.0         0.0   Inferno  
3     Overpass      Vertigo          0.0       Dust2       Train    Mirage  
4         Nuke      Inferno          0.0    Overpass     Vertigo     Dust2

In [5]:
economy_df.head()

date  match_id  event_id         team_1         team_2 best_of  \
0  2020-03-01   2339402      4901             G2  Natus Vincere       5   
1  2020-03-01   2339402      4901             G2  Natus Vincere       5   
2  2020-03-01   2339402      4901             G2  Natus Vincere       5   
3  2020-02-29   2339401      4901  Natus Vincere       Astralis       3   
4  2020-02-29   2339401      4901  Natus Vincere       Astralis       3   

     _map t1_start t2_start    1_t1     2_t1     3_t1     4_t1     5_t1  \
0    Nuke        t       ct  4350.0   1100.0  22100.0   9350.0  25750.0   
1   Dust2       ct        t  3900.0   7400.0  23250.0  28500.0  31900.0   
2  Mirage        t       ct  4150.0  14300.0   2000.0  24800.0   9000.0   
3   Dust2        t       ct  4150.0  18050.0  21000.0  25850.0  25000.0   
4    Nuke       ct        t  4200.0  10000.0  22000.0  24500.0  27550.0   

      6_t1     7_t1     8_t1     9_t1    10_t1    11_t1    12_t1    13_t1  \
0  10400.0  24600.0   8150.0  26700.0  23400.0   4300.0  25900.0  11950.0   
1  31700.0  18950.0  30200.0  28650.0  30350.0  30150.0  11100.0  23700.0   
2  23150.0  21850.0  23700.0  10450.0  26250.0   8800.0  24950.0  12100.0   
3  25000.0  27250.0  26150.0  26300.0  27850.0  26750.0  27450.0  27850.0   
4  29350.0  31950.0  31850.0  31750.0  32850.0  32150.0  31750.0  31850.0   

     14_t1    15_t1   16_t1    17_t1    18_t1    19_t1    20_t1    21_t1  \
0  24850.0  21900.0  4150.0  10650.0  27300.0  27000.0  30950.0      NaN   
1   8550.0  26350.0  4050.0   9400.0  21900.0  12700.0  11300.0   3100.0   
2  24350.0  18250.0  4300.0  19400.0   8900.0      NaN      NaN      NaN   
3  18300.0  27850.0  4000.0  21100.0   9100.0   3100.0  22100.0  23350.0   
4  33050.0  33150.0  4250.0   3000.0  21150.0  11750.0  28050.0  25900.0   

     22_t1    23_t1    24_t1    25_t1    26_t1    27_t1    28_t1    29_t1  \
0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1  26250.0  21300.0  23950.0  27450.0  27550.0  28050.0  26250.0  26250.0   
2      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
3      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
4      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

   30_t1    1_t2     2_t2     3_t2     4_t2     5_t2     6_t2     7_t2  \
0    NaN  4250.0  20250.0  24600.0  29300.0  30650.0  31450.0  32050.0   
1    NaN  3500.0  18550.0   7300.0   1500.0  21800.0  12000.0  21050.0   
2    NaN  4200.0  21200.0  24150.0  27050.0  31350.0  30650.0  31050.0   
3    NaN  4250.0   9300.0   2100.0  19300.0  27250.0   9850.0  24800.0   
4    NaN  4200.0  17950.0   9050.0   1000.0  22850.0   7500.0  24400.0   

      8_t2     9_t2    10_t2    11_t2    12_t2    13_t2    14_t2    15_t2  \
0  31450.0  32050.0  30950.0  29300.0  30200.0  31550.0  32350.0  33050.0   
1  24450.0   6850.0  26850.0  23100.0  25650.0  26800.0  26750.0  28250.0   
2  28150.0  29650.0  30950.0  31550.0  32950.0  32250.0  31650.0  33350.0   
3  12200.0  27550.0  26100.0   7450.0  27650.0  24500.0  19100.0  18050.0   
4  24700.0   9700.0  27150.0  21850.0  21900.0   8150.0  25200.0  20450.0   

    16_t2    17_t2    18_t2    19_t2    20_t2    21_t2    22_t2    23_t2  \
0  4250.0  20300.0   8250.0   1300.0  22200.0      NaN      NaN      NaN   
1  4000.0  18850.0  15850.0  23000.0  26850.0  29100.0  26300.0  26850.0   
2  4350.0  14300.0  22850.0      NaN      NaN      NaN      NaN      NaN   
3  4150.0  15100.0  18450.0  23150.0  28150.0  27850.0      NaN      NaN   
4  4300.0  19300.0  27400.0  31700.0  29650.0  12150.0      NaN      NaN   

     24_t2   25_t2    26_t2    27_t2    28_t2    29_t2  30_t2  1_winner  \
0      NaN     NaN      NaN      NaN      NaN      NaN    NaN       2.0   
1  19050.0  3500.0  26450.0  27450.0  27500.0  29050.0    NaN       2.0   
2      NaN     NaN      NaN      NaN      NaN      NaN    NaN       2.0   
3      NaN     NaN      NaN      NaN      NaN      NaN    N

In [6]:
players_df.head()

date player_name           team       opponent        country  \
0  2020-02-26      Brehze  Evil Geniuses         Liquid  United States   
1  2020-02-26        CeRq  Evil Geniuses         Liquid       Bulgaria   
2  2020-02-26       EliGE         Liquid  Evil Geniuses  United States   
3  2020-02-26       Ethan  Evil Geniuses         Liquid  United States   
4  2020-02-26         NAF         Liquid  Evil Geniuses         Canada   

   player_id  match_id  event_id         event_name  best_of     map_1 map_2  \
0       9136   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke   
1      11219   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke   
2       8738   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke   
3      10671   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke   
4       8520   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke   

     map_3  kills  assists  deaths  hs  flash_assists  kast  kddiff   adr  \
0  Inferno     57       14      61  29            0.0  71.1      -4  79.9   
1  Inferno     54       10      54  18            4.0  65.1       0  71.7   
2  Inferno     55       10      51  28            1.0  67.5       4  77.9   
3  Inferno     43        5      54  18            2.0  65.1     -11  58.7   
4  Inferno     52       22      46  23            9.0  77.1       6  75.9   

   fkdiff  rating  m1_kills  m1_assists  m1_deaths  m1_hs  m1_flash_assists  \
0       0    1.04        11           3         18      5               0.0   
1       2    0.98        11           2         17      4               2.0   
2       1    1.08        15           3         12      9               0.0   
3      -4    0.83        11           1         15      6               1.0   
4      -1    1.08        10           5         12      3               3.0   

   m1_kast  m1_kddiff  m1_adr  m1_fkdiff  m1_rating  m2_kills  m2_assists  \
0     65.2         -7    60.8         -1       0.70      30.0         7.0   
1     60.9         -6    68.9         -1       0.75      26.0         6.0   
2     69.6          3    77.0          3       1.32      24.0         3.0   
3     65.2         -4    60.7         -2       0.73      22.0         3.0   
4     65.2         -2    51.5          0       0.83      29.0         6.0   

   m2_deaths  m2_hs  m2_flash_assists  m2_kast  m2_kddiff  m2_adr  m2_fkdiff  \
0       24.0   16.0               0.0     73.5        6.0    99.2        6.0   
1       19.0    8.0               1.0     76.5        7.0    80.1        3.0   
2       24.0   14.0               0.0     64.7        0.0    72.9       -1.0   
3       21.0    8.0               1.0     70.6        1.0    67.9       -2.0   
4       21.0   16.0               0.0     82.4        8.0   101.9        0.0   

   m2_rating  m3_kills  m3_assists  m3_deaths  m3_hs  m3_flash_assists  \
0       1.38      16.0         4.0       19.0    8.0               0.0   
1       1.24      17.0         2.0       18.0    6.0               1.0   
2       0.97      16.0         4.0       15.0    5.0               1.0   
3       1.00      10.0         1.0       18.0    4.0               0.0   
4       1.35      13.0        11.0       13.0    4.0               6.0   

   m3_kast  m3_kddiff  ...  m3_fkdiff  m3_rating  kills_ct  deaths_ct  \
0     73.1       -3.0  ...       -5.0       0.91      34.0       30.0   
1     53.8       -1.0  ...        0.0       0.87      37.0       25.0   
2     69.2        1.0  ...       -1.0       1.04      31.0       17.0   
3     57.7       -8.0  ...        0.0       0.69      33.0       23.0   
4     80.8        0.0  ...       -1.0       0.98      28.0       17.0   

   kddiff_ct  adr_ct  kast_ct  rating_ct  kills_t  deaths_t  kddiff_t  adr_t  \
0        4.0    81.6     79.2       1.10     23.0      31.0      -8.0   77.5   
1       12.0    77.4     72.9       1.16     17.0      29.0     -12.0   63.9   
2       14.0    96.6     71.4       1.39     24.0      34.0     -10.0   64.2 

The data collected has data from all professional CS:GO matches, including matches from relatively unknown teams. For that reason, we will be limiting the datasets to the matches played between the top 30 teams in the HLTV rankings.

In [7]:
min_rank = 30
results_df = results_df[(results_df.rank_1<min_rank)&(results_df.rank_2<min_rank)]

picks_df     = picks_df  [picks_df  .match_id.isin(results_df.match_id.unique())]
economy_df   = economy_df[economy_df.match_id.isin(results_df.match_id.unique())]
players_df   = players_df[players_df.match_id.isin(results_df.match_id.unique())]

# Results DataFrame

## Distribution of scores

In [8]:
winner_1 = results_df[results_df.result_1>=results_df.result_2].result_1.values
loser_1  = results_df[results_df.result_1>=results_df.result_2].result_2.values

winner_2 = results_df[results_df.result_1<results_df.result_2].result_2.values
loser_2  = results_df[results_df.result_1<results_df.result_2].result_1.values

winner = np.concatenate((winner_1,winner_2))
loser = np.concatenate((loser_1,loser_2))
scores_df = pd.DataFrame(np.vstack((winner,loser)).T,columns=['winner','loser'])

In [9]:
gb = scores_df.groupby(by=['winner','loser'])['winner'].count()/scores_df.shape[0]
overtime_percentage = str(round(gb[gb.index.get_level_values(0)!=16].sum()*100,1))+'%'

gb = round(gb[gb>10**-3]*100,1)

index_plot = np.array(gb.index.get_level_values(0).astype('str'))+'-'+np.array(
    gb.index.get_level_values(1).astype('str'))

fig = go.Figure()
fig.add_trace(go.Scatter(x=index_plot,y=gb.values, name='results'))
fig.update_layout(xaxis_type='category',title='Scores distribution',xaxis_title='Score',yaxis_title='Percentage of matches (%)')

In [10]:
overtime_percentage

'9.7%'

We can see that on regular time (disregarding overtime), the most common score is 16-14 (achieved in 10.7% of the matches) and the rarest score is 16-0 (achieved in only 0.2% of the matches), with intermediate scores falling somewhere in between. 

9.7% of the matches go to overtime.

The results may differ if we consider matches played by non top-tier teams.

## Most CT sided map

There has long been a dispute in CS:GO to determine the most CT-sided maps, and always present discussion if having a heavily one-sided map is a desirable outcome. Here we determine this characteristic by computing the average scores obtained in each side of the map and then comparing both sides.

In [11]:
ct_1 = results_df[['date','_map','ct_1']].rename(columns={'ct_1':'ct'})
ct_2 = results_df[['date','_map','ct_2']].rename(columns={'ct_2':'ct'})
ct = pd.concat((ct_1,ct_2))

In [12]:
t_1 = results_df[['date','_map','t_1']].rename(columns={'t_1':'t'})
t_2 = results_df[['date','_map','t_2']].rename(columns={'t_2':'t'})
t = pd.concat((t_1,t_2))

In [13]:
t = t.sort_values('date')
ct = ct.sort_values('date')

In [14]:
maps = ['Cache','Cobblestone','Dust2','Inferno','Mirage','Nuke','Overpass','Train','Vertigo']

In [15]:
series_t, series_ct, how_ct = {},{},{}
for i, key in enumerate(maps):
    t_map = t[t._map == maps[i]]
    ct_map = ct[ct._map == maps[i]]
    y_t = t_map.t.rolling(min_periods = 20, window= 200, center=True).sum().values
    y_ct = ct_map.ct.rolling(min_periods = 20, window= 200, center=True).sum().values
    
    series_t[key] = pd.Series(data=y_t,index=t_map.date)
    series_ct[key] = pd.Series(data=y_ct,index=ct_map.date)
    
    how_ct[key] = series_ct[key]/(series_ct[key]+series_t[key])//0.001/10

In [16]:
def add_trace(_map):
    fig.add_trace(go.Scatter(x=how_ct[_map].index, y=how_ct[_map].values, name=_map))

In [17]:
fig = go.Figure()
for _map in maps:
    add_trace(_map)
fig.add_trace(go.Scatter(x=['2015-11-01', '2020-03-12'], y=[50,50],
                         mode='lines',line=dict(color='grey'),showlegend=False))
fig.update_layout(title='Distribution of rounds between CT and T sides',
                  yaxis_title='Percentage of round won on the CT-side (%)')
fig.show()

There are long stretches without data for a map in the graph. This happens because maps are added and removed from the map pool constantly.

<b>Nuke</b> and <b>Train</b> oscilatte as being the most CT-sided maps, having around 57% of the rounds won on the CT-side, while
<b>Dust2</b> and <b>Cache</b> are historically the most T-sided maps.

It is interesting to note that <b>Inferno</b> was known for being a heavily CT-sided map prior to 2016, which was one of the reasons to update it. Since its update, <b>Inferno</b> has actually been the most balanced map in this aspect.



## Maps played per period

About the maps:
 - <b>Mirage</b>, <b>Train</b>, <b>Inferno</b> and <b>Overpass</b> are the maps from which we have the most data available. They are also the maps present on the map pool for the longest time;

 - <b>Cache</b>, <b>Cobblestone</b> and <b>Dust2</b> have been played less, but have also been outside the map pool for the longest periods:

 - <b>Nuke</b> is historically the least played map, even though it has been present in the map pool for a long time. The only explanation for this stems from the teams' unfamiliarity with the map;

 - <b>Vertigo</b> has limited data available as it was the most recently added map in the map pool.

In [18]:
print('Total number of matches played on the map:')
results_df.groupby('_map').date.count()

Total number of matches played on the map:


_map
Cache           900
Cobblestone     898
Default           2
Dust2           892
Inferno        1325
Mirage         1617
Nuke            750
Overpass       1150
Train          1384
Vertigo          99
Name: date, dtype: int64

In CS:GO, the most reputable tournaments are the Majors. These tournaments are normally played twice a year and have a prize pool of $1,000,000. More information about the subject can be seen here: https://liquipedia.net/counterstrike/Majors

For the next step, we are going to discretize the 'date' column in a dataframe into a 'time_period' column. This new column will refer to the most recently played major tournament.

As an example, following this binning technique, we are currently on the Berlin 2019 period, as that was the most recently played tournament.

In [19]:
majors = [{'tournament':'01. Cluj-Napoca 2015','start_date':'2015-10-28'},
          {'tournament':'02. Columbus 2016','start_date':'2016-03-29'},
          {'tournament':'03. Cologne 2016','start_date':'2016-07-05'},
          {'tournament':'04. Atlanta 2017','start_date':'2017-01-22'},
          {'tournament':'05. Krakow 2017','start_date':'2017-07-16'},
          {'tournament':'06. Boston 2018','start_date':'2018-01-26'},
          {'tournament':'07. London 2018','start_date':'2018-09-20'},
          {'tournament':'08. Katowice 2019','start_date':'2019-02-28'},
          {'tournament':'09. Berlin 2019','start_date':'2019-09-05'}]

In [20]:
def create_col_time_period(df):
    df['time_period'] = ''
    
    for major_start in majors:
        df.loc[(df['date']>=major_start['start_date']),'time_period'] = major_start['tournament']
    
    return df

In [21]:
results_df = create_col_time_period(results_df)
economy_df = create_col_time_period(economy_df)
picks_df = create_col_time_period(picks_df)
players_df = players_df.merge(results_df[['match_id','time_period']],'left',on='match_id')

In [22]:
results_df_team_1 = results_df[['time_period','team_1','_map','ct_1','t_2','ct_2','t_1']
                      ].rename(columns={'team_1':'team'})
results_df_team_2 = results_df[['time_period','team_2','_map','ct_1','t_2','ct_2','t_1']
                      ].rename(columns={'team_2':'team'})
results_df_teams = pd.concat((results_df_team_1,results_df_team_2))[['time_period','team','_map']]

In [23]:
gb = results_df_teams.groupby(['time_period','_map']).team.count()
gb_text = round(gb*100/gb.groupby('time_period').sum(),1).reset_index().rename(columns={'team':'percentage'})
gb_text.percentage = gb_text.percentage.astype(str)+'%'
gb = gb.reset_index()

In [24]:
fig = go.Figure()
for _map in maps:
    fig.add_bar(name=_map,x=gb[gb._map==_map].time_period,y=gb[gb._map==_map].team,
                text=gb_text[gb_text._map==_map].percentage,textposition='inside')

fig.update_layout(barmode='stack',legend=dict(traceorder='normal'),yaxis_title='Number of maps played',font=dict(size=10))
fig.show()

As pointed out previously, <b>Nuke</b> is historically the least popular map in the pool. This has been changing recently, as teams that used to permaban the map have moved on to banning maps like Vertigo.

<b>Vertigo</b>, as the newest and most unconventional map, is also the most unpopular map, probably due to the many changes it has had in its short competitive term.

The period between Columbus and Cologne 2016 has the least amount of maps played and is also the shortest (under 4 months), while the period between Boston and London 2018 has the highest amount of maps played and is also the longest (over 7 months).

## Best teams on each map

In this section, let's search for the best teams in each map. The victory percentage for the teams on each map is readily available in many e-sports sites like hltv.org, so it would be pointless to present the information the same way. For this reason, instead of pointing out the percentages, we are going to rank the best teams on each map and each side (CT and T) for every time period.

In [25]:
results_df_team_1_ct = results_df_team_1.rename(columns={'ct_1':'ct_team','t_2':'t_opponent'}).drop(columns=['ct_2','t_1'])
results_df_team_2_ct = results_df_team_2.rename(columns={'ct_2':'ct_team','t_1':'t_opponent'}).drop(columns=['ct_1','t_2'])
results_df_ct = pd.concat((results_df_team_1_ct,results_df_team_2_ct),sort=True)

results_df_team_1_t = results_df_team_1.rename(columns={'t_1':'t_team','ct_2':'ct_opponent'}).drop(columns=['ct_1','t_2'])
results_df_team_2_t = results_df_team_2.rename(columns={'t_2':'t_team','ct_1':'ct_opponent'}).drop(columns=['ct_2','t_1'])
results_df_t = pd.concat((results_df_team_1_t,results_df_team_2_t),sort=True)

In [26]:
results_df_ct['side_diff'] = results_df_ct['ct_team']-results_df_ct['t_opponent']
results_df_ct['side_sum'] = results_df_ct['ct_team']+results_df_ct['t_opponent']

results_df_t['side_diff'] = results_df_t['t_team']-results_df_t['ct_opponent']
results_df_t['side_sum']  = results_df_t['t_team'] +results_df_t['ct_opponent']

results_df_ct.head()

_map  ct_team  t_opponent           team      time_period  side_diff  \
9     Mirage        9           6         fnatic  09. Berlin 2019          3   
21  Overpass        4           4         fnatic  09. Berlin 2019          0   
22      Nuke        7           8  Natus Vincere  09. Berlin 2019         -1   
23     Dust2        5          10  Natus Vincere  09. Berlin 2019         -5   
24     Train        3           7          forZe  09. Berlin 2019         -4   

    side_sum  
9         15  
21         8  
22        15  
23        15  
24        10

In [27]:
def groupby_time_map_team(results_df_side):
    gb = results_df_side.groupby(['time_period','_map','team'])['side_diff','side_sum'].sum()
    gb['side_diff_per_game'] = gb['side_diff']/(gb['side_sum']/15)
    gb = gb.sort_values(['time_period','_map','side_diff_per_game'],ascending=[1,1,0])

    for major in majors:
        col = major['tournament']
        _filter = (gb.side_sum > gb.loc[col].side_sum.mean()*3/4)
        gb.loc[col] = gb.loc[_filter][gb.loc[_filter].index.get_level_values(0)==col]

    gb.dropna(inplace=True)    

    return gb

In [28]:
gb_ct = groupby_time_map_team(results_df_ct)
gb_t = groupby_time_map_team(results_df_t)

In [29]:
def plot_ranking_teams_sides(gb):
    rankings_teams = {}
    for _map in maps:
        rankings_teams[_map] = pd.DataFrame(index=range(1,6),)
        rankings_teams[_map].index.name = 'ranking'
        rankings_teams[_map].style.set_caption(_map)

        for major in majors:
            col = major['tournament']
            try:
                rankings_teams[_map][col] = gb.loc[col,_map]['side_diff_per_game'][:5].index
            except:
                pass
        print('\n'+_map+':')
        display(rankings_teams[_map])

In [30]:
print('T-side Rankings:\n')
plot_ranking_teams_sides(gb_t)

T-side Rankings:


Cache:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                        NiP       mousesports             Envy   
2                     fnatic          Astralis           Cloud9   
3                     Splyce         Renegades      mousesports   
4                 Luminosity            Liquid          GODSENT   
5                     Liquid             OpTic               G2   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  
ranking                                                                   
1                   FaZe       Renegades          Liquid             NiP  
2                  North      Luminosity            FaZe          Liquid  
3                 fnatic  Space Soldiers           TYLOO      Virtus.pro  
4                     SK              SK          Gambit         AVANGAR  
5                     G2              G2              SK             NRG


Cobblestone:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                Tempo Storm            Liquid      VG.CyberZen   
2                HellRaisers              Envy                X   
3                 Virtus.pro            fnatic       Virtus.pro   
4                      OpTic           GODSENT           Gambit   
5                        NiP        Luminosity             Envy   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018  
ranking                                                   
1                     SK              SK  Space Soldiers  
2                    BIG  Space Soldiers              G2  
3                 Gambit          Cloud9     HellRaisers  
4                     G2             NiP         GODSENT  
5                 Cloud9           North          fnatic


Dust2:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                     fnatic        Luminosity        Renegades   
2                       ENCE     Natus Vincere           Gambit   
3                     Cloud9               CLG           Cloud9   
4                mousesports              Envy               SK   
5                     Liquid       Tempo Storm             Envy   

        06. Boston 2018 07. London 2018 08. Katowice 2019 09. Berlin 2019  
ranking                                                                    
1           HellRaisers          Liquid       mousesports     mousesports  
2                Liquid            FaZe                G2   Natus Vincere  
3                 North        Astralis             CR4ZY        Astralis  
4                  FaZe              G2           Windigo            FaZe  
5           mousesports             BIG            Liquid              G2


Inferno:


01. Cluj-Napoca 2015 02. Columbus 2016 04. Atlanta 2017  \
ranking                                                           
1                Tempo Storm              FaZe        Immortals   
2                      OpTic        Luminosity           fnatic   
3                   Astralis          Dignitas            PENTA   
4                        TSM              Envy           Cloud9   
5                   Selfless       mousesports      mousesports   

        05. Krakow 2017 06. Boston 2018 07. London 2018 08. Katowice 2019  \
ranking                                                                     
1         Natus Vincere             NiP        Astralis            Sprout   
2         Vega Squadron   Natus Vincere             NRG          Astralis   
3                   NRG         Windigo           OpTic            Liquid   
4                  FaZe           OpTic        Vitality              ENCE   
5                fnatic            Envy          fnatic     Natus Vincere   

        09. Berlin 2019  
ranking                  
1           100 Thieves  
2                 forZe  
3                   NiP  
4           mousesports  
5                 FURIA


Mirage:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                        TSM          Astralis              TSM   
2                   Dignitas          Dignitas          Kinguin   
3                    Ancient             TYLOO         Astralis   
4                   Astralis              CSGL          Epsilon   
5                  Renegades              FaZe           Liquid   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                     SK          Gambit            FaZe   Natus Vincere   
2                GODSENT     mousesports        Imperial           OpTic   
3                    CLG            FaZe   Natus Vincere     mousesports   
4               Astralis          Cloud9           North     HellRaisers   
5            HellRaisers             CLG     mousesports            LDLC   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                   CR4ZY          Liquid  
2             mousesports          Spirit  
3                Valiance            FaZe  
4                  Sprout            ENCE  
5                   FURIA       Renegades


Nuke:


03. Cologne 2016 04. Atlanta 2017 05. Krakow 2017 06. Boston 2018  \
ranking                                                                     
1                    NiP           Gambit     mousesports        Astralis   
2                 Liquid           Heroic              G2  Space Soldiers   
3             Virtus.pro             FaZe            Envy   Natus Vincere   
4               Dignitas            North      Virtus.pro          Heroic   
5               Echo Fox               G2        Astralis          Liquid   

        07. London 2018 08. Katowice 2019 09. Berlin 2019  
ranking                                                    
1              Astralis           Tricked        Astralis  
2                  ENCE               NiP           FURIA  
3                 OpTic               NRG        Vitality  
4                Heroic             OpTic            FaZe  
5           mousesports       mousesports   Evil Geniuses


Overpass:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                        TSM                G2    Natus Vincere   
2                          ?             OpTic              NiP   
3                   Astralis               NiP            OpTic   
4                     fnatic          Astralis             FaZe   
5                HellRaisers       HellRaisers           Cloud9   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1               Astralis              SK         GODSENT        Astralis   
2               FlipSid3  Space Soldiers             NRG             NRG   
3                Kinguin            FaZe        Astralis            ENCE   
4                 Heroic           OpTic             NiP   Natus Vincere   
5                 Gambit           North           North          Cloud9   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                  Liquid           FURIA  
2                  Heroic          fnatic  
3                   OpTic        Astralis  
4                    MIBR         Tricked  
5                Vitality             NiP


Train:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                        NiP              FaZe           Cloud9   
2                     fnatic            fnatic               SK   
3                 Luminosity            Liquid            OpTic   
4                      Vexed          Astralis                X   
5              Natus Vincere               NiP         Astralis   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                    BIG   Natus Vincere   Natus Vincere       Renegades   
2          Natus Vincere        FlipSid3             NRG        Astralis   
3                 Liquid             NiP         Windigo           North   
4                 Gambit           OpTic         GODSENT     mousesports   
5                   FaZe          Cloud9     mousesports   Natus Vincere   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1           Natus Vincere          Sprout  
2                     NRG           FURIA  
3                Valiance             NiP  
4                  fnatic        Astralis  
5                   North     mousesports


Vertigo:


09. Berlin 2019
ranking                
1               GODSENT
2                    G2
3                  MIBR
4                   NiP
5                Heroic

In [31]:
print('CT-side Rankings:\n')
plot_ranking_teams_sides(gb_ct)

CT-side Rankings:


Cache:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                      Enemy                G2           fnatic   
2                     fnatic       Tempo Storm         Astralis   
3                     Cloud9                SK          Epsilon   
4                       Envy       HellRaisers      HellRaisers   
5                         G2       mousesports           Cloud9   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  
ranking                                                                   
1            mousesports  Space Soldiers        Astralis         AVANGAR  
2                 Cloud9          Gambit     HellRaisers             BIG  
3                    NiP             NiP            FaZe          Liquid  
4                     SK            FaZe         AVANGAR       Renegades  
5              Immortals     HellRaisers              G2          Cloud9


Cobblestone:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                     fnatic            Cloud9                X   
2                   FlipSid3              Envy        Immortals   
3                 Luminosity         Renegades          Epsilon   
4                HellRaisers               NiP            OpTic   
5                         SK       HellRaisers               SK   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018  
ranking                                                   
1                     G2     mousesports          Liquid  
2                     SK      Virtus.pro             AGO  
3             Virtus.pro          fnatic  Space Soldiers  
4              Renegades   Natus Vincere          fnatic  
5                  North       Renegades         GODSENT


Dust2:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                   Astralis     Natus Vincere           Gambit   
2                     fnatic          Astralis         Astralis   
3                          ?            fnatic      mousesports   
4                HellRaisers              FaZe          GODSENT   
5                     Cloud9                G2              NiP   

        06. Boston 2018 07. London 2018 08. Katowice 2019 09. Berlin 2019  
ranking                                                                    
1              Astralis        Astralis             OpTic         GODSENT  
2           HellRaisers            LDLC             North            ENCE  
3                 North   Natus Vincere          Vitality          fnatic  
4           mousesports            ENCE              FaZe           North  
5                  FaZe           North     Natus Vincere   Natus Vincere


Inferno:


01. Cluj-Napoca 2015 02. Columbus 2016 04. Atlanta 2017  \
ranking                                                           
1                    Ancient     Natus Vincere    Natus Vincere   
2                     fnatic          Dignitas               G2   
3                  Renegades       mousesports         Astralis   
4                 Luminosity        Virtus.pro             FaZe   
5                   Conquest                G2            PENTA   

        05. Krakow 2017 06. Boston 2018 07. London 2018 08. Katowice 2019  \
ranking                                                                     
1             Immortals        Astralis        Vitality          Astralis   
2                  FaZe          Liquid        Astralis       mousesports   
3                Liquid            MIBR          Heroic          Valiance   
4                 North          Cloud9            FaZe           AVANGAR   
5              Astralis           North            MIBR            Liquid   

        09. Berlin 2019  
ranking                  
1                Liquid  
2                    G2  
3              Astralis  
4                fnatic  
5              Vitality


Mirage:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1              Natus Vincere          Astralis          GODSENT   
2                       ENCE        Luminosity           Cloud9   
3                       FaZe           Kinguin           Heroic   
4                   Astralis            Cloud9      mousesports   
5                 Luminosity     Natus Vincere    Natus Vincere   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                  OpTic          Cloud9           OpTic        Astralis   
2                 fnatic            FaZe        Astralis            MIBR   
3               Astralis           OpTic  Space Soldiers            ENCE   
4                     SK          Heroic       Renegades      Complexity   
5              Immortals     mousesports   Natus Vincere        Vitality   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                Valiance         Tricked  
2                   CR4ZY   Evil Geniuses  
3                  fnatic   Natus Vincere  
4                     NiP             BIG  
5           Natus Vincere       MAD Lions


Nuke:


03. Cologne 2016 04. Atlanta 2017 05. Krakow 2017 06. Boston 2018  \
ranking                                                                     
1               Dignitas         FlipSid3              G2        Astralis   
2               Astralis             FaZe     mousesports           North   
3                    NiP             Envy        Astralis   Natus Vincere   
4                   Envy            North          Heroic             NiP   
5             Virtus.pro           Heroic             NiP     mousesports   

        07. London 2018 08. Katowice 2019 09. Berlin 2019  
ranking                                                    
1              Vitality              ENCE     mousesports  
2              Astralis     Natus Vincere         Tricked  
3                 North            Liquid        Astralis  
4           mousesports          Vitality          Sprout  
5                   NiP             North           North


Overpass:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                mousesports        Luminosity    Natus Vincere   
2                          ?                G2          GODSENT   
3                 Luminosity          Astralis            OpTic   
4                     fnatic          FlipSid3      mousesports   
5                        NiP               CLG               SK   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                    BIG            FaZe             NRG            ENCE   
2                     SK              SK        Astralis            FaZe   
3                  North             NiP             BIG            LDLC   
4            HellRaisers        Astralis            FaZe          Liquid   
5                 Gambit              G2              G2        Astralis   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                   North   Natus Vincere  
2                  Liquid          Sprout  
3                     NiP     mousesports  
4                Astralis           FURIA  
5                Vitality         Tricked


Train:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                     Gambit             Orbit               SK   
2                 Luminosity       Tempo Storm           Gambit   
3                     Cloud9               NRG           fnatic   
4                          ?        Luminosity          GODSENT   
5                     Liquid     Natus Vincere             FaZe   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1          Natus Vincere             AGO        Astralis            ENCE   
2                    NiP          fnatic        Imperial            FaZe   
3            mousesports          Liquid          Cloud9     mousesports   
4                     SK              SK            FaZe        Astralis   
5               Astralis          Cloud9     HellRaisers   Natus Vincere   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                     NRG         AVANGAR  
2                Astralis           CR4ZY  
3                    ENCE     mousesports  
4           Natus Vincere        Astralis  
5                    FaZe   Natus Vincere


Vertigo:


09. Berlin 2019
ranking                
1              Astralis
2                    G2
3                Heroic
4                Liquid
5                   NiP

# Economy DataFrame

## Round victory probability by equipment value

Counter-strike has an economic system that governs the acquisitions of armor, weapons and grenades by the players. The rules of this system have changed many times in the past. 

Currently, round loss bonuses are based on a count of a team's round loss bonus. This count is increased by one after every loss and decreased by one after every win (minimum 0). The money returned after losing a round is:

 - 0 Losses: &dollar;1400;
 - 1 Loss: &dollar;1900;
 - 2 Losses: &dollar;2400;
 - 3 Losses: &dollar;2900;
 - 4+ Losses: &dollar;3400.

Previously to 2019, a win would reset the round loss bonus back to &dollar;1400 per player. Now, a win reduces the loss count by one.
Teams begin the half with a loss count of 1, so that losing the pistol round is not as damaging to the economy.

Players start the half with &dollar;800, which is enough to buy either armour or an improved pistol, but not both, nor better weapons. That is why rounds 1 and 16 are called pistol rounds.

Winning a round by eliminations grants &dollar;3250 to the winning team. If the win was achieved by defusing the bomb as CT or by having it detonate as T, the reward is of 3500 dollars.

Another way of getting money in the match is by killing players in the opposing team. The money received per kill varies according to the weapon wielded:
- &dollar;100: Sniper rifle kills;
- &dollar;300: pistol, assault rifle and grenade kills;
- &dollar;600: SMG kills;
- &dollar;900: Shotgun kills;
- &dollar;1500: Knife kills.

In the HLTV economy section of the matches, the sum of the equipment value of the teams is categorized according to 4 equipment value ranges:
 - &dollar; 0-5 K: Eco;
 - &dollar; 5-10 K: Forced Pistols;
 - &dollar; 10-20 K: Semi-buy;
 - &dollar; 20+ K: Full buy.
 
In this notebooks, the Semi-buy category was split into two new categories, according to equipment value:
 - &dollar;10-15 K: ForcedSMGs;
 - &dollar;15-20 K: ForcedBuy.
 
This change was added because the &dollar;10-20 K money range is too broad and groups together very distinct sets of equipment.

In [32]:
economy_df.head()

date  match_id  event_id         team_1         team_2 best_of  \
0  2020-03-01   2339402      4901             G2  Natus Vincere       5   
1  2020-03-01   2339402      4901             G2  Natus Vincere       5   
2  2020-03-01   2339402      4901             G2  Natus Vincere       5   
3  2020-02-29   2339401      4901  Natus Vincere       Astralis       3   
4  2020-02-29   2339401      4901  Natus Vincere       Astralis       3   

     _map t1_start t2_start    1_t1     2_t1     3_t1     4_t1     5_t1  \
0    Nuke        t       ct  4350.0   1100.0  22100.0   9350.0  25750.0   
1   Dust2       ct        t  3900.0   7400.0  23250.0  28500.0  31900.0   
2  Mirage        t       ct  4150.0  14300.0   2000.0  24800.0   9000.0   
3   Dust2        t       ct  4150.0  18050.0  21000.0  25850.0  25000.0   
4    Nuke       ct        t  4200.0  10000.0  22000.0  24500.0  27550.0   

      6_t1     7_t1     8_t1     9_t1    10_t1    11_t1    12_t1    13_t1  \
0  10400.0  24600.0   8150.0  26700.0  23400.0   4300.0  25900.0  11950.0   
1  31700.0  18950.0  30200.0  28650.0  30350.0  30150.0  11100.0  23700.0   
2  23150.0  21850.0  23700.0  10450.0  26250.0   8800.0  24950.0  12100.0   
3  25000.0  27250.0  26150.0  26300.0  27850.0  26750.0  27450.0  27850.0   
4  29350.0  31950.0  31850.0  31750.0  32850.0  32150.0  31750.0  31850.0   

     14_t1    15_t1   16_t1    17_t1    18_t1    19_t1    20_t1    21_t1  \
0  24850.0  21900.0  4150.0  10650.0  27300.0  27000.0  30950.0      NaN   
1   8550.0  26350.0  4050.0   9400.0  21900.0  12700.0  11300.0   3100.0   
2  24350.0  18250.0  4300.0  19400.0   8900.0      NaN      NaN      NaN   
3  18300.0  27850.0  4000.0  21100.0   9100.0   3100.0  22100.0  23350.0   
4  33050.0  33150.0  4250.0   3000.0  21150.0  11750.0  28050.0  25900.0   

     22_t1    23_t1    24_t1    25_t1    26_t1    27_t1    28_t1    29_t1  \
0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1  26250.0  21300.0  23950.0  27450.0  27550.0  28050.0  26250.0  26250.0   
2      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
3      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
4      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

   30_t1    1_t2     2_t2     3_t2     4_t2     5_t2     6_t2     7_t2  \
0    NaN  4250.0  20250.0  24600.0  29300.0  30650.0  31450.0  32050.0   
1    NaN  3500.0  18550.0   7300.0   1500.0  21800.0  12000.0  21050.0   
2    NaN  4200.0  21200.0  24150.0  27050.0  31350.0  30650.0  31050.0   
3    NaN  4250.0   9300.0   2100.0  19300.0  27250.0   9850.0  24800.0   
4    NaN  4200.0  17950.0   9050.0   1000.0  22850.0   7500.0  24400.0   

      8_t2     9_t2    10_t2    11_t2    12_t2    13_t2    14_t2    15_t2  \
0  31450.0  32050.0  30950.0  29300.0  30200.0  31550.0  32350.0  33050.0   
1  24450.0   6850.0  26850.0  23100.0  25650.0  26800.0  26750.0  28250.0   
2  28150.0  29650.0  30950.0  31550.0  32950.0  32250.0  31650.0  33350.0   
3  12200.0  27550.0  26100.0   7450.0  27650.0  24500.0  19100.0  18050.0   
4  24700.0   9700.0  27150.0  21850.0  21900.0   8150.0  25200.0  20450.0   

    16_t2    17_t2    18_t2    19_t2    20_t2    21_t2    22_t2    23_t2  \
0  4250.0  20300.0   8250.0   1300.0  22200.0      NaN      NaN      NaN   
1  4000.0  18850.0  15850.0  23000.0  26850.0  29100.0  26300.0  26850.0   
2  4350.0  14300.0  22850.0      NaN      NaN      NaN      NaN      NaN   
3  4150.0  15100.0  18450.0  23150.0  28150.0  27850.0      NaN      NaN   
4  4300.0  19300.0  27400.0  31700.0  29650.0  12150.0      NaN      NaN   

     24_t2   25_t2    26_t2    27_t2    28_t2    29_t2  30_t2  1_winner  \
0      NaN     NaN      NaN      NaN      NaN      NaN    NaN       2.0   
1  19050.0  3500.0  26450.0  27450.0  27500.0  29050.0    NaN       2.0   
2      NaN     NaN      NaN      NaN      NaN      NaN    NaN       2.0   
3      NaN     NaN      NaN      NaN      NaN      NaN    N

In [33]:
money_columns = ['2_t1','3_t1','4_t1','5_t1','6_t1','7_t1','8_t1','9_t1','10_t1','11_t1','12_t1','13_t1','14_t1'
                ,'15_t1','17_t1','18_t1','19_t1','20_t1','21_t1','22_t1','23_t1','24_t1','25_t1','26_t1','27_t1',
                 '28_t1','29_t1','30_t1',
                '2_t2','3_t2','4_t2','5_t2','6_t2','7_t2','8_t2','9_t2','10_t2','11_t2','12_t2','13_t2','14_t2'
                ,'15_t2','17_t2','18_t2','19_t2','20_t2','21_t2','22_t2','23_t2','24_t2','25_t2','26_t2','27_t2',
                 '28_t2','29_t2','30_t2']

economy_categories = {0:{'name':'eco','start':0,'end':5000},
                      1:{'name':'forcedPistols','start':5000,'end':10000},
                      2:{'name':'forcedSMGs','start':10000,'end':15000},
                      3:{'name':'forcedBuy','start':15000,'end':20000},
                      4:{'name':'fullBuy','start':20000,'end':50000}
                      }

In [34]:
for col in money_columns:
    for key, category in economy_categories.items():
        economy_df.loc[(economy_df[col]>category['start']) & (economy_df[col]<=category['end']),col] = key
    for key, category in economy_categories.items():
        economy_df.loc[economy_df[col]==key,col] = category['name']

In [35]:
def get_economy_stats(category):

    wins_by_side_t1 = pd.DataFrame([[0,0,0],[0,0,0]],index=['ct','t'],columns=['sum','count','mean'])
    wins_by_side_t2 = pd.DataFrame([[0,0,0],[0,0,0]],index=['ct','t'],columns=['sum','count','mean'])

    for _round in range(2,16):
        gb_1 = economy_df[economy_df[str(_round)+'_t1']==category].rename(columns={'t1_start':'side'}).groupby('side')[str(_round)+'_winner']
        gb_1 = gb_1.agg(['sum','count','mean'])

        gb_3 = economy_df[economy_df[str(_round+15)+'_t1']==category].rename(columns={'t2_start':'side'}).groupby('side')[str(_round+15)+'_winner']
        gb_3 = gb_3.agg(['sum','count','mean'])

        gb_1 = gb_1.reindex(['ct','t'], fill_value=0)
        gb_3 = gb_3.reindex(['ct','t'], fill_value=0)

        wins_by_side_t1 = wins_by_side_t1 + gb_1 + gb_3

    wins_by_side_t1['sum'] = 2*wins_by_side_t1['count']-wins_by_side_t1['sum']

    for _round in range(2,16):
        gb_2 = economy_df[economy_df[str(_round)+'_t2']==category].rename(columns={'t2_start':'side'}).groupby('side')[str(_round)+'_winner']
        gb_2 = gb_2.agg(['sum','count','mean'])

        gb_4 = economy_df[economy_df[str(_round+15)+'_t2']==category].rename(columns={'t1_start':'side'}).groupby('side')[str(_round+15)+'_winner']
        gb_4 = gb_4.agg(['sum','count','mean'])

        gb_2 = gb_2.reindex(['ct','t'], fill_value=0)
        gb_4 = gb_4.reindex(['ct','t'], fill_value=0)

        wins_by_side_t2 = wins_by_side_t2 + gb_2 + gb_4

    wins_by_side_t2['sum'] = wins_by_side_t2['sum']-wins_by_side_t2['count']

    wins_by_side = wins_by_side_t1 + wins_by_side_t2

    wins_by_side['mean'] = wins_by_side['sum']/wins_by_side['count']//0.001/10
    wins_by_side['num_per_game'] = wins_by_side['count']/economy_df.shape[0]//0.1/10
    wins_by_side = wins_by_side[['mean','num_per_game']]
    
    return wins_by_side

In [36]:
economy_stats = {}
mean_victories_df = pd.DataFrame(index=['ct','t'])
num_per_game_df = pd.DataFrame(index=['ct','t'])

for category in economy_categories.values():
    cat = category['name']
    economy_stats[cat] = get_economy_stats(cat)
    mean_victories_df[cat] = economy_stats[cat]['mean']
    num_per_game_df[cat] = economy_stats[cat]['num_per_game']

print('\nVictory probability (%):')
display(mean_victories_df)
print('\nNumber per game:')
display(num_per_game_df)


Victory probability (%):


eco  forcedPistols  forcedSMGs  forcedBuy  fullBuy
ct  5.9           19.3        30.5       54.9     62.4
t   4.3           18.4        31.9       60.4     56.4


Number per game:


eco  forcedPistols  forcedSMGs  forcedBuy  fullBuy
ct  2.1            1.9         1.1        1.5     16.9
t   2.1            1.8         1.0        2.6     16.0

The tables above present the probability of winning rounds according to the team's equipment value category, and the number of rounds of each category type in a map. The results do not take into consideration the equipment category of the opposing team.

Teams are 40% more likely to win <b>eco</b> rounds on the CT-side, 10% more likely to win <b>forcedBuy</b> rounds on the T-side and 11% more likely to win <b>fullBuy</b> rounds on the CT-side.

A team has on average 6 <b>non-fullBuy</b> rounds in a map. The number of rounds in each category does not vary much between CT and T sides, which is surprising, as the CT-side economy usually seems to be the hardest one to maintain. 

## Pistols ranking

In [37]:
gb_team_1_first_pistol   = economy_df.rename(columns={'team_1':'team','t1_start':'side'}).groupby(['side','time_period','team'])['1_winner'].agg(['mean','count'])
gb_team_1_second_pistol  = economy_df.rename(columns={'team_1':'team','t2_start':'side'}).groupby(['side','time_period','team'])['16_winner'].agg(['mean','count'])

gb_team_2_first_pistol   = economy_df.rename(columns={'team_2':'team','t2_start':'side'}).groupby(['side','time_period','team'])['1_winner'].agg(['mean','count'])
gb_team_2_second_pistol  = economy_df.rename(columns={'team_2':'team','t1_start':'side'}).groupby(['side','time_period','team'])['16_winner'].agg(['mean','count'])

In [38]:
gb = (2-gb_team_1_first_pistol['mean'])*gb_team_1_first_pistol['count']+(
    2-gb_team_1_second_pistol['mean'])*gb_team_1_second_pistol['count']+(
    gb_team_2_first_pistol['mean']-1)*gb_team_2_first_pistol['count']+(
    gb_team_2_second_pistol['mean']-1)*gb_team_2_second_pistol['count']

total_pistols = (gb_team_1_first_pistol['count']+gb_team_1_second_pistol['count']+gb_team_2_first_pistol['count']+gb_team_2_second_pistol['count'])

for major in majors[3:]:
    col = major['tournament']
    
    _filter = total_pistols > total_pistols.loc[:,col].quantile(0.3)
    
    gb.loc[:,col] = gb.loc[_filter,col]
    total_pistols.loc[:,col] = total_pistols.loc[_filter,col]
    
    gb.dropna(inplace=True)
    total_pistols.dropna(inplace=True)

mean_pistols = pd.DataFrame(gb/total_pistols)
mean_pistols.dropna(inplace=True)
mean_pistols.sort_values(['side','time_period',0],ascending=[1,1,0],inplace=True)

In [39]:
def get_rankings_pistols_side(side):
    ranking_pistols_side = pd.DataFrame(index=range(1,8))
    ranking_pistols_side.index.name = 'ranking'

    for major in majors[3:]:
        col = major['tournament']
        ranking_pistols_side[col] = mean_pistols.loc[side,col][0][:7].index
    
    return ranking_pistols_side

In [40]:
print('\nRankings Pistols CT-side:')
display(get_rankings_pistols_side('ct'))
print('\nRankings Pistols T-side:')
display(get_rankings_pistols_side('t'))


Rankings Pistols CT-side:


04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                   FaZe            FaZe           OpTic      Virtus.pro   
2                    CLG           North             BIG        Astralis   
3             Virtus.pro          Cloud9        Astralis            MIBR   
4                     SK      Virtus.pro           North           OpTic   
5                   Envy           OpTic             NRG       Renegades   
6                 Cloud9     HellRaisers  Space Soldiers      Complexity   
7                  North  Space Soldiers          Cloud9          Liquid   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                    FaZe          Heroic  
2                      G2             BIG  
3               Renegades          Liquid  
4                    MIBR           CR4ZY  
5                   OpTic         AVANGAR  
6                Astralis        Astralis  
7                   FURIA            ENCE


Rankings Pistols T-side:


04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                   FaZe     mousesports          Heroic          Liquid   
2                 Cloud9       Renegades        Imperial        Astralis   
3                    CLG           OpTic             NRG              G2   
4            mousesports     HellRaisers     mousesports      Virtus.pro   
5                     SK              SK  Space Soldiers             NRG   
6                  North          Cloud9         GODSENT            FaZe   
7              Immortals          Gambit        Astralis          Cloud9   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                Valiance             BIG  
2           Natus Vincere     100 Thieves  
3                Astralis          fnatic  
4                  fnatic            FaZe  
5                 Windigo          Sprout  
6                  Liquid       Renegades  
7                Vitality   Evil Geniuses

# Players DataFrame

## Players ranking by map

In [41]:
players_df.head()

date player_name           team opponent        country  player_id  \
0  2020-02-26      Brehze  Evil Geniuses   Liquid  United States       9136   
1  2020-02-26      Brehze  Evil Geniuses   Liquid  United States       9136   
2  2020-02-26      Brehze  Evil Geniuses   Liquid  United States       9136   
3  2020-02-26        CeRq  Evil Geniuses   Liquid       Bulgaria      11219   
4  2020-02-26        CeRq  Evil Geniuses   Liquid       Bulgaria      11219   

   match_id  event_id         event_name  best_of     map_1 map_2    map_3  \
0   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke  Inferno   
1   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke  Inferno   
2   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke  Inferno   
3   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke  Inferno   
4   2339385      4901  IEM Katowice 2020        3  Overpass  Nuke  Inferno   

   kills  assists  deaths  hs  flash_assists  kast  kddiff   adr  fkdiff  \
0     57       14      61  29            0.0  71.1      -4  79.9       0   
1     57       14      61  29            0.0  71.1      -4  79.9       0   
2     57       14      61  29            0.0  71.1      -4  79.9       0   
3     54       10      54  18            4.0  65.1       0  71.7       2   
4     54       10      54  18            4.0  65.1       0  71.7       2   

   rating  m1_kills  m1_assists  m1_deaths  m1_hs  m1_flash_assists  m1_kast  \
0    1.04        11           3         18      5               0.0     65.2   
1    1.04        11           3         18      5               0.0     65.2   
2    1.04        11           3         18      5               0.0     65.2   
3    0.98        11           2         17      4               2.0     60.9   
4    0.98        11           2         17      4               2.0     60.9   

   m1_kddiff  m1_adr  m1_fkdiff  m1_rating  m2_kills  m2_assists  m2_deaths  \
0         -7    60.8         -1       0.70      30.0         7.0       24.0   
1         -7    60.8         -1       0.70      30.0         7.0       24.0   
2         -7    60.8         -1       0.70      30.0         7.0       24.0   
3         -6    68.9         -1       0.75      26.0         6.0       19.0   
4         -6    68.9         -1       0.75      26.0         6.0       19.0   

   m2_hs  m2_flash_assists  m2_kast  m2_kddiff  m2_adr  m2_fkdiff  m2_rating  \
0   16.0               0.0     73.5        6.0    99.2        6.0       1.38   
1   16.0               0.0     73.5        6.0    99.2        6.0       1.38   
2   16.0               0.0     73.5        6.0    99.2        6.0       1.38   
3    8.0               1.0     76.5        7.0    80.1        3.0       1.24   
4    8.0               1.0     76.5        7.0    80.1        3.0       1.24   

   m3_kills  m3_assists  m3_deaths  m3_hs  m3_flash_assists  m3_kast  \
0      16.0         4.0       19.0    8.0               0.0     73.1   
1      16.0         4.0       19.0    8.0               0.0     73.1   
2      16.0         4.0       19.0    8.0               0.0     73.1   
3      17.0         2.0       18.0    6.0               1.0     53.8   
4      17.0         2.0       18.0    6.0               1.0     53.8   

   m3_kddiff  ...  m3_rating  kills_ct  deaths_ct  kddiff_ct  adr_ct  kast_ct  \
0       -3.0  ...       0.91      34.0       30.0        4.0    81.6     79.2   
1       -3.0  ...       0.91      34.0       30.0        4.0    81.6     79.2   
2       -3.0  ...       0.91      34.0       30.0        4.0    81.6     79.2   
3       -1.0  ...       0.87      37.0       25.0       12.0    77.4     72.9   
4       -1.0  ...       0.87      37.0       25.0       12.0    77.4     72.9   

   rating_ct  kills_t  deaths_t  kddiff_t  adr_t  kast_t  rating_t  \
0       1.10     23.0      31.0      -8.0   77.5    60.0      0.97   
1       1.10     23.0      31.0      -8.0   77.5    60.0      0.97   
2       1.10     23.0      31.0      -8.0

In [42]:
all_maps_columns = ['date','time_period','country','player_name','team','opponent','player_id',
                    'match_id','event_id','event_name','best_of']
each_map_columns = ['kills','assists','deaths','hs','flash_assists','kast','kddiff','adr','fkdiff','rating']

In [43]:
map1_columns = ['map_1']+['m1_'+ x for x in each_map_columns]
map2_columns = ['map_2']+['m2_'+ x for x in each_map_columns]
map3_columns = ['map_3']+['m3_'+ x for x in each_map_columns]

In [44]:
out_columns = all_maps_columns+['_map']+each_map_columns

players_df_by_map_columns = pd.DataFrame(columns=out_columns)

In [45]:
#Countries that contribute the most to the professional scene by number of matches
players_df.groupby('country')['country'].count().sort_values(ascending=False)[:30]

country
Denmark                   13562
Sweden                    11031
United States              9216
France                     7116
Brazil                     6463
Poland                     5415
Russia                     4390
Ukraine                    3640
Canada                     3295
Germany                    3050
Finland                    2358
Australia                  2020
Kazakhstan                 1917
Turkey                     1801
Slovakia                   1791
Norway                     1737
Bulgaria                   1402
China                       856
Bosnia and Herzegovina      852
Belgium                     851
Netherlands                 823
Estonia                     750
Serbia                      619
Czech Republic              587
United Kingdom              585
Spain                       551
Hungary                     417
Lithuania                   307
Jordan                      299
Indonesia                   212
Name: country, dtype: int64

In [46]:
curr_map = {}
curr_map[0] = players_df[(all_maps_columns+map1_columns)]
curr_map[1] = players_df[(all_maps_columns+map2_columns)]
curr_map[2] = players_df[(all_maps_columns+map3_columns)]

curr_map[0].columns = out_columns
curr_map[1].columns = out_columns
curr_map[2].columns = out_columns

all_maps = pd.concat(   (   pd.concat(   (curr_map[0],curr_map[1])    ), curr_map[2]   )   )

In [47]:
gb2 = all_maps.groupby(['time_period','player_id','_map'])
threshold_maps_played = 7
all_maps2 = gb2.filter(lambda x:x.player_name.count()>threshold_maps_played)
all_maps2.head()

date      time_period        country player_name           team  \
0  2020-02-26  09. Berlin 2019  United States      Brehze  Evil Geniuses   
1  2020-02-26  09. Berlin 2019  United States      Brehze  Evil Geniuses   
2  2020-02-26  09. Berlin 2019  United States      Brehze  Evil Geniuses   
3  2020-02-26  09. Berlin 2019       Bulgaria        CeRq  Evil Geniuses   
4  2020-02-26  09. Berlin 2019       Bulgaria        CeRq  Evil Geniuses   

  opponent  player_id  match_id  event_id         event_name  best_of  \
0   Liquid       9136   2339385      4901  IEM Katowice 2020        3   
1   Liquid       9136   2339385      4901  IEM Katowice 2020        3   
2   Liquid       9136   2339385      4901  IEM Katowice 2020        3   
3   Liquid      11219   2339385      4901  IEM Katowice 2020        3   
4   Liquid      11219   2339385      4901  IEM Katowice 2020        3   

       _map  kills  assists  deaths   hs  flash_assists  kast  kddiff   adr  \
0  Overpass   11.0      3.0    18.0  5.0            0.0  65.2    -7.0  60.8   
1  Overpass   11.0      3.0    18.0  5.0            0.0  65.2    -7.0  60.8   
2  Overpass   11.0      3.0    18.0  5.0            0.0  65.2    -7.0  60.8   
3  Overpass   11.0      2.0    17.0  4.0            2.0  60.9    -6.0  68.9   
4  Overpass   11.0      2.0    17.0  4.0            2.0  60.9    -6.0  68.9   

   fkdiff  rating  
0    -1.0    0.70  
1    -1.0    0.70  
2    -1.0    0.70  
3    -1.0    0.75  
4    -1.0    0.75

In [48]:
gb = all_maps2.groupby(['time_period','_map','player_name'],sort=False)['rating','kddiff'].mean()
rankings = gb.sort_values(['time_period','_map','rating'],ascending=[1,1,0])

In [49]:
rankings_players = {}
for _map in maps:
    rankings_players[_map] = pd.DataFrame(index=range(1,21))
    rankings_players[_map].index.name = 'ranking'
    
    for major in majors:
        col = major['tournament']
        try:
            rankings_players[_map][col] = rankings.loc[col,_map].rating[:20].index
        except:
            pass

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:9: PerformanceWarning:

indexing past lexsort depth may impact performance.



Best players on each map accordding to their average Rating 2.0:

In [50]:
for _map in maps:
    print('\n'+_map+':')
    display(rankings_players[_map])


Cache:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                      oskar             MICHU             HEN1   
2                  WorldEdit            ScreaM      olofmeister   
3                olofmeister             felps            ANGE1   
4                       NiKo              shox             Zero   
5                   coldzera          innocent         Kjaerbye   
6                     kennyS            MINISE          mixwell   
7                         JW              NiKo         coldzera   
8                       NBK-             oskar           Furlan   
9                      Shara             boltz        WorldEdit   
10                     KRIMZ               nex             Pimp   
11                  MAiNLiNE              HEN1            MICHU   
12                       mou            USTILO             NiKo   
13                       nex            bondik             Snax   
14                    koosta             STYKO            Happy   
15                      allu         SHOOWTiME           flusha   
16                      shox               RpK           v1c7oR   
17                    shroud               NAF            Xyp9x   
18                      Uber       olofmeister           dennis   
19                 seang@res           dupreeh              REZ   
20                    dennis              RUSH          BARBARR   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1               innocent           boltz       EspiranTo            Jame   
2                  Calyx             NAF            NiKo             NAF   
3                    fer        XANTARES            nexa         Twistzz   
4                     HS        coldzera           woxic          f0rest   
5               XANTARES           oskar          device          tabseN   
6                  suNny          FalleN           ISSAA        XANTARES   
7                  ANGE1             nex           Ethan          flusha   
8                   NiKo           GruBy        GuardiaN       EspiranTo   
9                  STYKO           chelo             NAF          qikert   
10                kennyS            NiKo        XANTARES           EliGE   
11                 Nifty           byali         Twistzz   Gratisfaction   
12                 boltz           tarik            apEX             jks   
13                draken            allu     olofmeister           fitch   
14               ShahZaM     pashaBiceps          tabseN          dennis   
15              Stewie2K           fitch           Calyx            CeRq   
16                  HEN1           AdreN           GruBy           oskar   
17             GeT_RiGhT          Hobbit         dupreeh            nexa   
18                cajunb          ScreaM          kennyS           dephh   
19                  rain          USTILO            NBK-           suNny   
20              coldzera         Twistzz            rain            NiKo   

        08. Katowice 2019  
ranking                    
1                    NBK-  
2                   ZywOo  
3                     RpK  
4                   KRIMZ  
5                      JW  
6                 Brollan  
7                  AmaNEk  
8                    Jame  
9                    apEX  
10                   ALEX  
11                    NAF  
12                   shox  
13                  twist  
14                  stavn  
15                 blameF  
16                 kennyS  
17                  mertz  
18                 buster  
19                 qikert  
20                   Xizt


Cobblestone:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                       Zero            kennyS           Hobbit   
2                      felps              apEX             Dima   
3                       Snax               AZR             shox   
4                   queztone            ScreaM         XANTARES   
5                      oskar       olofmeister            tarik   
6                     f0rest             oskar             NiKo   
7                     MINISE             nitr0              mou   
8                       mouz            MODDII            spaze   
9                      Happy             EliGE            Dosia   
10                     AdreN              RUSH           Savage   
11                  Kjaerbye            flusha             mouz   
12                     boltz             byali            ANGE1   
13                    Furlan            Magisk          DavCost   
14                    LUCAS1          coldzera             NBK-   
15                     STYKO              Snax           kennyS   
16                 markeloff                JW             Snax   
17                       AZR         stanislaw           Magisk   
18                     KRIMZ             DEVIL             HEN1   
19                    flamie         Skadoodle             SicK   
20                    rallen            FalleN            valde   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018  
ranking                                                   
1               coldzera             paz             paz  
2                  Calyx          Furlan           Calyx  
3               XANTARES        XANTARES        XANTARES  
4                    fer        snatchie           woxic  
5                Twistzz          f0rest             NAF  
6                  MICHU             REZ           KRIMZ  
7                 tabseN          s1mple             fer  
8                  bodyy             NAF            ngiN  
9              Skadoodle           GruBy         Twistzz  
10                 felps           suNny        coldzera  
11                 EliGE            HEN1          s1mple  
12                  niko           oskar           EliGE  
13                  apEX           byali    disco doplan  
14                   fnx          FalleN      electronic  
15             autimatic            ropz          v1c7oR  
16          disco doplan          LUCAS1          bondik  
17                kennyS     pashaBiceps          FalleN  
18              freddieb           kNgV-          flusha  
19                   nex           Lekr0    somedieyoung  
20                 AdreN             fer           Lekr0


Dust2:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                       NiKo             oskar            AdreN   
2                       HEN1            seized           device   
3                      oskar              Pimp            felps   
4                      STYKO              shox           bubble   
5                olofmeister             denis              mou   
6                       juho            chrisJ         coldzera   
7                     chrisJ            flamie            ANGE1   
8                     dennis          coldzera             HEN1   
9                   GuardiaN             boltz              fnx   
10                    device            FalleN           shroud   
11                 Skadoodle              NiKo           FalleN   
12                       fox            ScreaM              nex   
13                    bubble            rallen           dennis   
14                     xartE             felps              jks   
15                      Hiko              rain        autimatic   
16                     EliGE            shroud            twist   
17                    cajunb            flusha          ShahZaM   
18                       nex              Zeus        GeT_RiGhT   
19                    flusha               fnx           k0nfig   
20                      allu             bodyy             rain   

        06. Boston 2018 07. London 2018 08. Katowice 2019 09. Berlin 2019  
ranking                                                                    
1                device           mertz             ZywOo          syrsoN  
2                 woxic          s1mple        electronic           Maden  
3              XANTARES          Magisk             woxic          tabseN  
4                 ISSAA           valde            s1mple          hampus  
5                   nex            NiKo              ropz          device  
6                 Xyp9x           woxic              rain            k1to  
7                  allu          tabseN              NiKo           KRIMZ  
8                tabseN         dupreeh             EliGE            ropz  
9               dupreeh        XANTARES            kennyS          dennis  
10                MICHU             NAF            k0nfig        XANTARES  
11                 NiKo           EliGE           Twistzz           ZywOo  
12                EliGE            shox               NAF           woxic  
13               Magisk          AmaNEk              Jame            NiKo  
14               kennyS          device          Kjaerbye            Jame  
15                 Snax           Xyp9x            blameF             nex  
16             coldzera         Twistzz              gade          s1mple  
17               sergej          kennyS            AmaNEk            rain  
18               tiziaN            Jame            Edward      electronic  
19                  paz          sergej             SHiPZ           SHiPZ  
20             Kjaerbye            aizy            frozen        coldzera


Inferno:


01. Cluj-Napoca 2015 02. Columbus 2016 04. Atlanta 2017  \
ranking                                                           
1                      twist            device              nex   
2                        NAF            Edward            Calyx   
3                olofmeister              rain           tabseN   
4                      Nifty          queztone            Friis   
5                     ScreaM               nex             HEN1   
6                      oskar             oskar         XANTARES   
7                       Uber            flusha           device   
8                     kennyS            ScreaM         coldzera   
9                        fnx            flamie            boltz   
10                     Lekr0              Zero         innocent   
11                     felps          kioShiMa             allu   
12                    flusha               fox           LUCAS1   
13                      Hiko           dupreeh         GuardiaN   
14                    flamie              aizy           k0nfig   
15                        JW            TENZKI             rain   
16                   SmithZz              NBK-             NiKo   
17                  coldzera              Snax           ScreaM   
18                     boltz            seized              fer   
19                     KRIMZ              shox               HS   
20                     mitch            RUBINO           FalleN   

        05. Krakow 2017 06. Boston 2018 07. London 2018 08. Katowice 2019  \
ranking                                                                     
1                  rain             NAF           mertz            poizon   
2            electronic          Magisk           ZywOo            syrsoN   
3                  NiKo           SHiPZ          Aerial            qikert   
4                 DEVIL             nex        kioShiMa              Jame   
5                s1mple          device          s1mple            v1c7oR   
6                  CeRq        coldzera          sergej             SHiPZ   
7               Twistzz            nexa          gla1ve          XANTARES   
8                LUCAS1          nukkye          device        electronic   
9                 EliGE           woxic            Jame            s1mple   
10             GuardiaN         mixwell            apEX            device   
11                hutji          s1mple            NBK-            sergej   
12             XANTARES           oskar           Happy           Twistzz   
13                 ngiN          k0nfig            allu             ZywOo   
14               flamie            JUGi          Magisk             oskar   
15               ScreaM         dupreeh           Xyp9x             Xyp9x   
16                FugLy         Aleksib       autimatic            Magisk   
17                KRIMZ           Ethan       stanislaw            yuurih   
18          olofmeister          draken           woxic          xsepower   
19               Magisk        kioShiMa          es3tag            frozen   
20               device        XANTARES          xseveN            gla1ve   

        09. Berlin 2019  
ranking                  
1                 BnTeT  
2                 ZywOo  
3                dennis  
4                 EliGE  
5                   jks  
6             Maikelele  
7                 jkaem  
8                 SHiPZ  
9               Plopski  
10             coldzera  
11               kennyS  
12               s1mple  
13            EspiranTo  
14                Jerry  
15               device  
16             KSCERATO  
17             xsepower  
18                  INS  
19                 ropz  
20                Liazz


Mirage:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                       NiKo            device             niko   
2                    BARBARR                DD           dennis   
3                   GuardiaN            cajunb           flusha   
4                     flamie         captainMo            jdm64   
5                       allu            Edward        autimatic   
6                       Uber          coldzera             NiKo   
7                       tabu          Kjaerbye           device   
8                     Spiidi               fnx          SEMPHIS   
9                       HEN1               fer            boltz   
10                   DeadFox            Summer         GuardiaN   
11                     EliGE           dupreeh         Stewie2K   
12                    chrisJ            MODDII            oskar   
13                    TENZKI            Magisk           k0nfig   
14                    RUBINO              RUSH           draken   
15                   dupreeh            FalleN            xelos   
16                     twist            shroud     disco doplan   
17                 WorldEdit          Stewie2K            valde   
18                       fer           mixwell            twist   
19                    f0rest            bubble           MODDII   
20                  coldzera            cadiaN           cajunb   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                 Rickeh            NiKo          s1mple          s1mple   
2                ShahZaM          kennyS        XANTARES            niko   
3                    fer        XANTARES            CeRq           ZywOo   
4                  EliGE          s1mple          k0nfig            Jame   
5                   NiKo           suNny          device            JUGi   
6                  twist        coldzera            NiKo           woxic   
7                 device            JUGi      electronic        XANTARES   
8                 koosta            rain          Hobbit         huNter-   
9                 cadiaN            apEX       autimatic           oskar   
10                k0nfig        GuardiaN           woxic           hAdji   
11               Twistzz           oskar           KRIMZ          chrisJ   
12                   paz          FalleN           Ethan          bondik   
13                s1mple     olofmeister           suNny             NAF   
14                 Calyx          Hobbit     olofmeister         Twistzz   
15              Kjaerbye         mixwell          sergej           valde   
16              XANTARES           EliGE            rain           Jerry   
17              coldzera             mir           SHiPZ      electronic   
18                 felps              HS            nexa        coldzera   
19              Stewie2K       autimatic       EspiranTo          Brehze   
20                  Snax             NAF            JUGi          AmaNEk   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                 huNter-           ZywOo  
2                    Jame        XANTARES  
3                    nexa          s1mple  
4                  s1mple          tabseN  
5                   faveN           EliGE  
6              electronic       EspiranTo  
7                   ZywOo    somedieyoung  
8                   EliGE            NiKo  
9                xsepower          magixx  
10                  jkaem          blameF  
11                 blameF           stavn  
12                    fer             NAF  
13                 sergej         Twistzz  
14                 poizon            ropz  
15                 ottoNd            Jame  
16                  dycha     iDISBALANCE  
17               coldzera          frozen  
18                  Etha


Nuke:


03. Cologne 2016 04. Atlanta 2017 05. Krakow 2017 06. Boston 2018  \
ranking                                                                     
1                dupreeh           kennyS            shox          s1mple   
2                   roca             NiKo          kennyS          device   
3                 f0rest        markeloff           byali        XANTARES   
4                 USTILO        WorldEdit            ropz          Brehze   
5                 gla1ve            AdreN          device          gla1ve   
6                  byali              MSL          s1mple           EliGE   
7              GeT_RiGhT            valde             RpK         dupreeh   
8                 Magisk           Magisk            NBK-      electronic   
9                    TaZ          Twistzz          es3tag           Xyp9x   
10                 STYKO             JUGi         dupreeh           Ethan   
11               friberg            oskar           oskar          Magisk   
12                   ryx           cajunb           Happy     pashaBiceps   
13                cajunb             Snax            NiKo            JUGi   
14                  apEX       electronic            rain          kennyS   
15                  Hiko           k0nfig          chrisJ            aizy   
16                  allu            EliGE          ScreaM            ropz   
17                k0nfig             rain            Snax          es3tag   
18                 bodyy            byali            JUGi          sergej   
19               ShahZaM             aizy           valde            NiKo   
20                  Snax           MODDII     pashaBiceps          k0nfig   

        07. London 2018 08. Katowice 2019 09. Berlin 2019  
ranking                                                    
1                 ZywOo            s1mple          device  
2                 nitr0            device        KSCERATO  
3                cajunb              acoR            Sico  
4                gla1ve            f0rest          dexter  
5               dupreeh             ZywOo         huNter-  
6               Twistzz          Kjaerbye           ZywOo  
7                device              CeRq          syrsoN  
8                 valde        electronic          gla1ve  
9                sergej             EliGE           malta  
10               Magisk               jks             INS  
11                Xyp9x            Brehze          f0rest  
12               es3tag          coldzera          meyern  
13                 Snax           Twistzz          chrisJ  
14                bodyy             JaCkz            CeRq  
15               chrisJ             mertz             NAF  
16                 CeRq            sergej          es3tag  
17                mertz            Rickeh      electronic  
18               Brehze            yuurih            ropz  
19               tabseN             b0RUP          tabseN  
20                  mou              rain          s1mple


Overpass:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                     flusha              shox           s1mple   
2                     Magisk          Stewie2K           Magisk   
3                    dupreeh             oskar           flamie   
4                        NAF           dupreeh             NiKo   
5                     koosta               fer           bubble   
6                     MODDII            ScreaM           v1c7oR   
7                     s1mple            shroud         freddieb   
8                     k0nfig            device              NAF   
9                     kennyS            Magisk             RUSH   
10                   Ex6TenZ               NAF          mixwell   
11                    FalleN          coldzera        Maikelele   
12                  Kjaerbye              Snax           MODDII   
13                    device            f0rest           Edward   
14                    shroud               fnx            valde   
15                 WorldEdit         WorldEdit            jkaem   
16                       fnx           n0thing             aizy   
17               olofmeister               NEO           flusha   
18                       fer              RUSH            felps   
19                        JW         GeT_RiGhT           SZPERO   
20                    cajunb             bodyy            Lekr0   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                ShahZaM        coldzera          cromen            apEX   
2                 tabseN             fer          s1mple          tabseN   
3                  AdreN          s1mple            CeRq           ZywOo   
4                   SicK            rain           Ethan          s1mple   
5                 bondik           oskar         Brollan          AmaNEk   
6               XANTARES            ropz       EspiranTo           Ethan   
7                    fer           Calyx           FugLy         Aleksib   
8                    fnx            Zero          device            allu   
9                  Lekr0            NiKo             REZ        Kjaerbye   
10              Stewie2K             NAF          es3tag           woxic   
11                 boltz     olofmeister          Magisk         Brollan   
12               Twistzz          FalleN         dupreeh           mertz   
13                  JUGi         Ex6TenZ          qikert      electronic   
14              coldzera        GuardiaN          gla1ve            NBK-   
15              Kjaerbye          Magisk            nexa          Brehze   
16                s1mple          f0rest          v1c7oR            shox   
17                 Xyp9x           Nifty           valde          es3tag   
18                 ANGE1             MSL             NAF            NiKo   
19                  niko           GruBy          hampus            CeRq   
20                  NBK-          k0nfig          Furlan       autimatic   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                   TeSeS          yuurih  
2                    NiKo            roeJ  
3                     REZ            rain  
4                   ZywOo            ropz  
5                   EliGE            acoR  
6                    Jame        coldzera  
7                  blameF         Brollan  
8                  s1mple          Magisk  
9                 Boombl4        KSCERATO  
10                    NAF            NiKo  
11               coldzera             REZ  
12                  valde          sjuush  
13                dupreeh            VINI  
14                 Magisk            HEN1  
15                  nitr0        xsepower  
16                 qikert            aizy  
17                Twistzz          s1mple  
18                 poizo


Train:


01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                     rallen            f0rest           FalleN   
2                  facecrack              rain         coldzera   
3                     Furlan            bubble           bubble   
4                     FalleN              SicK              fer   
5                       repo            device           flusha   
6                  WorldEdit          coldzera            AdreN   
7                        fer               mou           device   
8                      jdm64            flamie            Lekr0   
9                         JW            Magisk           flamie   
10                  GuardiaN               ptr        autimatic   
11                    Magisk          Kjaerbye         Stewie2K   
12                 Skadoodle            flusha            twist   
13                 GeT_RiGhT              HEN1            suNny   
14                     Hyper         GeT_RiGhT           dennis   
15                  coldzera            FalleN           Savage   
16                      HEN1            Furlan         freddieb   
17                       AZR           mixwell         Kjaerbye   
18                    s1mple              Xizt             apEX   
19                    ub1que              NiKo          znajder   
20                    device                JW            felps   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1                  suNny           GruBy          Aerial          s1mple   
2              GeT_RiGhT          s1mple          s1mple          device   
3                 draken          device        XANTARES         Boombl4   
4                 s1mple          k0nfig            allu           Ethan   
5               XANTARES        XANTARES            nexa            NiKo   
6                 Hobbit             fer            JUGi             jks   
7                 device      electronic           woxic          Brehze   
8                 FalleN             RpK          device           woxic   
9                  AdreN          f0rest           Ethan           valde   
10                   nex          Furlan          sergej           jkaem   
11                chrisJ          flusha       autimatic           oskar   
12                 oskar             paz            NiKo          to1nou   
13                 ANGE1         mixwell         KrizzeN        GuardiaN   
14                   fer            SicK           oskar          sergej   
15                f0rest        Stewie2K          flusha            Jame   
16                Rickeh           boltz            ropz         huNter-   
17              coldzera           Lekr0          flamie          AmaNEk   
18                  NiKo       GeT_RiGhT      electronic        coldzera   
19                    HS              JW          buster           suNny   
20                LUCAS1        coldzera            CeRq           Xyp9x   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                  s1mple          s1mple  
2              electronic      electronic  
3                    CeRq         Brollan  
4                    nexa            mouz  
5                   Xyp9x         almazer  
6                    aizy        xsepower  
7                 Brollan            HEN1  
8                  Brehze        innocent  
9                    NiKo           nawwk  
10                   allu          f0rest  
11                  Ethan            ropz  
12                    jks         huNter-  
13                  JaCkz        KSCERATO  
14                 device            acoR  
15                 FalleN         Bubzkji  
16                dupreeh          Magisk  
17                 Aerial             emi  
18                     J


Vertigo:


08. Katowice 2019 09. Berlin 2019
ranking                                  
1                  k0nfig         Brollan
2                   jkaem           STYKO
3                   EliGE         huNter-
4                  device            zehN
5                 huNter-             jks
6                    nexa          device
7                   Xyp9x          Golden
8                     MSL           Liazz
9                    niko           STOMP
10                dupreeh           stavn
11               Stewie2K       Maikelele
12                refrezh          AmaNEk
13                  JaCkz           Maden
14              EspiranTo           nawwk
15                 Magisk            FL1T
16                    jks          sjuush
17                    NAF           reatz
18                     HS          cadiaN
19                 kennyS          es3tag
20                  LETN1           Xyp9x

## Players ranking all maps

In [51]:
ranking_players_df = pd.DataFrame()
ranking_players_df['player'] = players_df.player_name.unique()
ranking_players_df.set_index('player',inplace=True)

for major in majors:
    col = major['tournament']
    ranking_players_df[col] = 0
    
for _map in maps:
    for col in rankings_players[_map].columns:
        for i in range(1,21):
            ranking_players_df.loc[rankings_players[_map][col][i],col] += 21-i
            
rankings_players_again = {}

rankings_players_again = pd.DataFrame(index=range(1,21))
rankings_players_again.index.name = 'ranking'

for major in majors:
    col = major['tournament']
    rankings_players_again[col] = ranking_players_df[col].sort_values(ascending=False)[:20].index

Below it is shown the player rankings if it was only determined by the rating 2.0 across all maps. It can be considered as the ranking of most versatile fraggers. 

In [52]:
rankings_players_again

01. Cluj-Napoca 2015 02. Columbus 2016 03. Cologne 2016  \
ranking                                                           
1                      oskar             oskar             NiKo   
2                       NiKo            ScreaM           bubble   
3                olofmeister            device         coldzera   
4                  WorldEdit          coldzera           device   
5                   GuardiaN              shox           flusha   
6                     kennyS              rain            ANGE1   
7                        NAF            Magisk           dennis   
8                       HEN1            flamie             HEN1   
9                         JW            flusha           Magisk   
10                      Uber           dupreeh            AdreN   
11                    flusha            Edward        autimatic   
12                    Magisk               fer           FalleN   
13                     felps            f0rest              mou   
14                    FalleN               nex           flamie   
15                  coldzera              NiKo          mixwell   
16                    Furlan             felps            felps   
17                    flamie             boltz             niko   
18                     twist          Kjaerbye           Hobbit   
19                   dupreeh            shroud           v1c7oR   
20                     STYKO            FalleN         Stewie2K   

        04. Atlanta 2017 05. Krakow 2017 06. Boston 2018 07. London 2018  \
ranking                                                                    
1               XANTARES          s1mple          device          s1mple   
2                    fer        XANTARES        XANTARES           ZywOo   
3                  Calyx            NiKo          s1mple            Jame   
4                   NiKo           oskar           woxic           woxic   
5                 tabseN            rain           Ethan           mertz   
6               coldzera        coldzera            nexa          device   
7                  AdreN           GruBy            NiKo          tabseN   
8                Twistzz             NAF             NAF           valde   
9                ShahZaM          FalleN          Magisk         Twistzz   
10                device            ropz         dupreeh        XANTARES   
11                 suNny          kennyS      electronic             NAF   
12                kennyS           byali       EspiranTo            NiKo   
13                   nex          device            CeRq          Magisk   
14                 EliGE             fer           EliGE          sergej   
15                 boltz          f0rest             nex           Ethan   
16              innocent      electronic           ISSAA          gla1ve   
17                s1mple          Furlan        coldzera            apEX   
18                draken        GuardiaN            JUGi         dupreeh   
19                Rickeh             paz            allu          AmaNEk   
20                 ANGE1             RpK           Xyp9x           oskar   

        08. Katowice 2019 09. Berlin 2019  
ranking                                    
1                  s1mple           ZywOo  
2                   ZywOo          device  
3              electronic          s1mple  
4                    Jame         Brollan  
5                   EliGE            ropz  
6                  device        KSCERATO  
7                    nexa         huNter-  
8                    NiKo          tabseN  
9                  blameF          syrsoN  
10                  Xyp9x           EliGE  
11                huNter-            NiKo  
12                    NAF             jks  
13                   CeRq          dennis  
14                 k0nfig        XANTARES  
15                Twistzz           Maden  
16                 poizon        coldzera  
17                  jkaem      electronic  
18                Brolla

## K/D Graph

In [53]:
results_df_rank_part_1 = results_df[['match_id','team_1','rank_1']].rename(columns={'team_1':'team','rank_1':'team_rank'})
results_df_rank_part_2 = results_df[['match_id','team_2','rank_2']].rename(columns={'team_2':'team','rank_2':'team_rank'})
results_df_rank = pd.concat((results_df_rank_part_1,results_df_rank_part_2))

In [54]:
all_maps3 = all_maps2.merge(results_df_rank,'left',on=['match_id','team'])

In [55]:
players_series = all_maps3.groupby('player_name').team_rank.min()
players_list = list(players_series[players_series<=3].index)

In [56]:
gb = all_maps3.groupby(['time_period','player_name','country'])['kills','deaths','team_rank']
gb = gb.mean()[gb.count()['kills']>100]
gb = gb[gb.index.get_level_values(1).isin(players_list)]

gb['kills'] = gb['kills'].round(1)
gb['deaths'] = gb['deaths'].round(1)
gb['team_rank'] = gb['team_rank'].round(0).astype('int')
gb.reset_index(inplace=True)

In [57]:
gb['region'] = ''
gb.loc[(gb['country']=='Ukraine') | (gb['country']=='Russia') | (gb['country']=='Kazakhstan'),'region'] = 'CIS'
gb.loc[(gb['country']=='Brazil'),'region'] = 'Brazil'
gb.loc[(gb['country']=='France') | (gb['country']=='Belgium'),'region'] = 'France/Belgium'
gb.loc[(gb['country']=='United States') | (gb['country']=='Canada'),'region'] = 'North America'
gb.loc[(gb['country']=='Denmark'),'region'] = 'Denmark'
gb.loc[(gb['country']=='Sweden'),'region'] = 'Sweden'
gb.loc[(gb['country']=='Poland'),'region'] = 'Poland'
gb.loc[gb.country.isin(['Netherlands','Slovakia','Bosnia and Herzegovina',
                        'Norway','Czech Republic','Spain','Estonia','United Kingdom','Portugal','Turkey','Bulgaria', 'Finland']),'region'] = 'Rest of Europe'

gb = gb.sort_values(['time_period','region'])

In [58]:
gb['size'] = (100/(gb['team_rank']+2)).round(1)

In [59]:
fig = px.scatter(gb, x="deaths", y="kills", animation_frame="time_period", animation_group="player_name",
           size="size", color="region", hover_name="player_name", hover_data=["team_rank"],
                 range_x=[14,24],range_y=[14,24]
                )
#.for_each_trace(lambda t: t.update(name=t.name.split("=")[1]))
fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 2000
fig.layout.updatemenus[0].buttons[0].args[1]["transition"]["duration"] = 1300
fig.update_layout(xaxis_title='Deaths', yaxis_title = 'Kills')
fig.add_shape(type="line", x0=14, y0=14, x1=24, y1=24, line=dict(width=4, dash="dot"))
fig.update_shapes(dict(xref='x', yref='y'))
fig.show()

# Picks DataFrame

In [60]:
picks_df.head()

date      team_1         team_2  inverted_teams  match_id  event_id  \
3   2020-03-17  Complexity          forZe               1   2340279      5226   
5   2020-03-17         BIG         fnatic               1   2340397      5226   
15  2020-03-17       North  Natus Vincere               1   2340396      5226   
23  2020-03-16      Spirit           ENCE               1   2340391      5226   
30  2020-03-16     GODSENT       Vitality               1   2340063      5226   

   best_of  system t1_removed_1 t1_removed_2 t1_removed_3 t2_removed_1  \
3        3  123412      Inferno         Nuke          0.0     Overpass   
5        3  123412        Train        Dust2          0.0         Nuke   
15       3  123412        Train      Inferno          0.0      Vertigo   
23       3  123412     Overpass        Dust2          0.0      Vertigo   
30       3  123412       Mirage     Overpass          0.0        Train   

   t2_removed_2 t2_removed_3 t1_picked_1 t2_picked_1 left_over  \
3       Vertigo          0.0       Dust2       Train    Mirage   
5       Vertigo          0.0     Inferno    Overpass    Mirage   
15       Mirage          0.0        Nuke       Dust2  Overpass   
23         Nuke          0.0     Inferno       Train    Mirage   
30      Inferno          0.0     Vertigo        Nuke     Dust2   

        time_period  
3   09. Berlin 2019  
5   09. Berlin 2019  
15  09. Berlin 2019  
23  09. Berlin 2019  
30  09. Berlin 2019

In [61]:
gb = picks_df.groupby('system').system.count()
gb = gb[gb>10]
gb

system
112221     208
121212     354
121234      81
122112     406
123412    1546
123421     159
Name: system, dtype: int64

The order 123412 (t1_remove, t2_remove, t1_pick, t2_pick, t1_remove, t2_remove, left_over) is by far the most common map picking system for bo3 matches.
For bo1 matches, there is a three-way split between the systems 122112, 112221 and 121212.

# Further exploration and predictions

If you think these insights are useful, I might update the dataset with data from 2014 and 2015.

What insights can you create from this data? Can you predict the probability of each:
 - team winning a map?
 - map being vetoed or selected?
 - team winning the match, combining predictions from map winners and map picks?
 
 Give it a try!
